/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mmo_rgb.glb 
Author: Masashi Kishimoto .inc (https://sketchfab.com/rosserraconia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-mmo-rpg-female-4k-high-contrast-18afe1b01497488ab1cd7d3c42fa3ab9
Title: FREE MMO RPG female 4k High-contrast
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Mmo(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('public/models/mmo_rgb.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="8b4736df827a4098a0986d9dfab50c43fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="1301_GongBenWuZang_Show3" position={[0, 623.312, 0]} scale={619.381}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_116" position={[-9.315, 750.248, -225.73]} rotation={[-Math.PI / 2, 0, 0]} scale={619.381} />
                    <group name="Object_118" position={[-9.315, 750.248, -225.73]} rotation={[-Math.PI / 2, 0, 0]} scale={619.381} />
                    <skinnedMesh name="Object_117" geometry={nodes.Object_117.geometry} material={materials['Material.005']} skeleton={nodes.Object_117.skeleton} />
                    <skinnedMesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials['Material.006']} skeleton={nodes.Object_119.skeleton} />
                  </group>
                </group>
                <group name="1301_gongbenwuzangHair_High" position={[-9.315, 750.248, -225.73]} rotation={[-Math.PI / 2, 0, 0]} scale={619.381} />
                <group name="1301_gongbenwuzangHair_High001" position={[-9.315, 750.248, -225.73]} rotation={[-Math.PI / 2, 0, 0]} scale={619.381} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('public/models/mmo_rgb.glb')
